version: '3.8'

services:
  client:
    image: vadymc/web-media-storage:latest
    env_file:
      - './client/.env'
    restart: always
    expose:
      - 3000
    environment:
      - NODE_ENV=production

  server:
    image: vadymc/web-media-storage-server:latest
    env_file:
      - './server/.env'
    restart: always
    expose:
      - 4000
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
      - client
